# Generated by Django 5.0.1 on 2024-02-01 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField()),
                ('company_address', models.TextField()),
                ('company_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_headline', models.CharField(max_length=255)),
                ('employee_location', models.CharField(max_length=255)),
                ('employee_followers', models.IntegerField()),
                ('employee_connections', models.IntegerField()),
                ('employee_education', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='indeed_job_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=123)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('date_of_post', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_list.company')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_list.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_list.experience'),
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('date_job_post', models.DateField()),
                ('job_description', models.CharField(max_length=255)),
                ('date_of_scrap', models.DateField()),
                ('job_id', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_list.company')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_list.source')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs_list.source'),
        ),
    ]
