# Generated by Django 5.0.1 on 2024-02-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0002_company_company_email_company_company_size'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adm',
            table='adm',
        ),
    ]
