# Generated by Django 5.0.1 on 2024-02-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0003_alter_adm_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adm',
            table=None,
        ),
    ]
