# Generated by Django 5.0.1 on 2024-02-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0004_alter_adm_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeed_job_list',
            name='custom_id',
            field=models.IntegerField(),
        ),
    ]
