# Generated by Django 5.0.1 on 2024-02-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0008_alter_indeed_job_list_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indeed_job_list',
            old_name='custom_id',
            new_name='id',
        ),
    ]
