# Generated by Django 5.0.1 on 2024-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0009_rename_custom_id_indeed_job_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeed_job_list',
            name='id',
            field=models.CharField(max_length=123, primary_key=True, serialize=False),
        ),
    ]
