# Generated by Django 5.0.1 on 2024-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0017_rename_custom_id_indeed_job_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeed_job_list',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indeed_job_list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indeed_job_list',
            name='job_title',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='indeed_job_list',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indeed_job_list',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='indeed_job_list',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
