# Generated by Django 5.0.1 on 2024-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0019_indeed_job_list_custom_id_alter_indeed_job_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='custom_id',
        ),
        migrations.AlterField(
            model_name='indeed_job_list',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
