# Generated by Django 5.0.1 on 2024-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0022_alter_indeed_job_list_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeed_job_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
