# Generated by Django 5.0.1 on 2024-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0023_alter_indeed_job_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='company',
        ),
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='date_of_post',
        ),
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='location',
        ),
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='indeed_job_list',
            name='tags',
        ),
    ]
