# Generated by Django 5.0.1 on 2024-02-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0027_rename_id_indeed_job_list_sid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='indeed_job_list',
            new_name='indeed_job',
        ),
    ]
