# Generated by Django 5.0.1 on 2024-02-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0028_rename_indeed_job_list_indeed_job'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='indeed_job',
            new_name='indeed_job_list',
        ),
    ]
