# Generated by Django 5.0.1 on 2024-02-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0029_rename_indeed_job_indeed_job_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indeed_job_list',
            old_name='sid',
            new_name='id',
        ),
    ]
