# Generated by Django 5.0.1 on 2024-02-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.CharField(default='Email', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(default='size', max_length=255),
        ),
    ]
