# Generated by Django 5.0.1 on 2024-01-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_email_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndeedJobList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_id', models.CharField(max_length=20, unique=True)),
                ('job_title', models.CharField(max_length=123)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('date_of_post', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
