# Generated by Django 5.0.1 on 2024-01-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_indeedjoblist_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeedjoblist',
            name='custom_id',
            field=models.CharField(max_length=20),
        ),
    ]
