# Generated by Django 5.0.1 on 2024-01-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_indeedjoblist_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='date_of_post',
        ),
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='location',
        ),
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='indeedjoblist',
            name='tags',
        ),
    ]
