# Generated by Django 5.0.1 on 2024-01-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contact_delete_indeedjoblist'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndeedJobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=123)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
