# Generated by Django 5.0.1 on 2024-01-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_indeedjoblist_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeedjoblist',
            name='job_title',
            field=models.CharField(max_length=15),
        ),
    ]
