# Generated by Django 5.0.1 on 2024-01-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_indeedjoblist_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indeedjoblist',
            old_name='job_title',
            new_name='name',
        ),
    ]
