# Generated by Django 5.0.1 on 2024-01-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contact_delete_indeedjoblist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
