# Generated by Django 5.0.1 on 2024-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_job_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_list',
            name='title',
            field=models.CharField(default='YourDefaultTitle', max_length=50),
        ),
    ]
