# Generated by Django 5.0.1 on 2024-01-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_job_list_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_list',
            name='title',
            field=models.CharField(default='Job_Title', max_length=50),
        ),
    ]
