# Generated by Django 5.0.1 on 2024-01-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_job_list_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_list',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job_list',
            name='title',
        ),
        migrations.AddField(
            model_name='job_list',
            name='company_name',
            field=models.CharField(default='Company Name', max_length=100),
        ),
        migrations.AddField(
            model_name='job_list',
            name='custom_id',
            field=models.CharField(default='Custom_ID', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='job_list',
            name='date_of_post',
            field=models.CharField(default='Date of Post', max_length=100),
        ),
        migrations.AddField(
            model_name='job_list',
            name='job_description',
            field=models.TextField(default='Job Description'),
        ),
        migrations.AddField(
            model_name='job_list',
            name='job_title',
            field=models.CharField(default='Job_Title', max_length=123),
        ),
        migrations.AddField(
            model_name='job_list',
            name='location',
            field=models.CharField(default='Job_location', max_length=100),
        ),
        migrations.AddField(
            model_name='job_list',
            name='salary_range',
            field=models.CharField(default='Salary', max_length=100),
        ),
        migrations.AddField(
            model_name='job_list',
            name='tags',
            field=models.CharField(default='Tags', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_list',
            name='id',
            field=models.AutoField(default='Primary Key', primary_key=True, serialize=False),
        ),
    ]
