# Generated by Django 5.0.1 on 2024-01-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_job_list_name_remove_job_list_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
