# Generated by Django 5.0.1 on 2024-01-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_sign_up_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sign_up',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
