# Generated by Django 5.0.1 on 2024-01-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_sign_up_email_alter_sign_up_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Job_list',
        ),
        migrations.DeleteModel(
            name='Sign_up',
        ),
    ]
