# Generated by Django 5.0.1 on 2024-01-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='indeed_job_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=123)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('date_of_post', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
            ],
        ),
    ]
