# Generated by Django 5.0.1 on 2024-01-30 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_indeed_job_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField()),
                ('company_address', models.TextField()),
                ('company_contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_headline', models.CharField(max_length=255)),
                ('employee_location', models.CharField(max_length=255)),
                ('employee_followers', models.IntegerField()),
                ('employee_connections', models.IntegerField()),
                ('employee_education', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.experience'),
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('date_job_post', models.DateField()),
                ('job_description', models.CharField(max_length=255)),
                ('date_of_scrap', models.DateField()),
                ('job_id', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.source')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.source'),
        ),
    ]
